### PR TITLE
Add support for phrases

### PR DESCRIPTION
**Pull request by MySmilingTurban**

### CODE REVIEW

**Comment by MySmilingTurban** [comment]
@Gauravjeetsingh veerji, can you do a quick PR review,
as this fix is really needed in the content making process rn

**Review by lbk003 — CHANGES_REQUESTED** [review]
Please add test - totally okay to have the test only for this change

**Comment by MySmilingTurban** [comment]
working on it

**Review by lbk003 — APPROVED** [review]
Please add a new ticket for unit tests

**Pull request merged**
