### PR TITLE
Updated workflow to deploy to all environments on merge

### PR DESCRIPTION
**Pull request by MySmilingTurban**

### CODE REVIEW

**Comment by MySmilingTurban** [comment]
The fix for the failing node.js workflow is a part of Latest PR, do let me know if you want me to add it here as well.

**Review by theamanjsryaz — APPROVED** [review]
Looks good to me

**Comment by theamanjs** [comment]
I approved this PR from my different account. 

PS @MySmilingTurban veerji I'm seeing this error in our CI CD logs https://github.com/KhalisFoundation/gurmukhi/actions/runs/5662586917/job/15342805397?pr=20

**Comment by MySmilingTurban** [comment]
@theamanjs veerji, that issue is fixed in #12 
shall I add it here as well?
could you please review with @theamanjs id, I guess it will be considered as approving member review

**Pull request merged**
